version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    #    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./whelp/:/home/whelp_user/whelp/
      - static_volume:/home/whelp_user/whelp/static/
      - media_volume:/home/whelp_user/whelp/media/
    #    ports:
    #      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  celery:
    build: .
    command: celery -A whelp worker -l info
    volumes:
      - ./whelp/:/home/whelp_user/whelp/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/home/whelp_user/whelp/static/
      - media_volume:/home/whelp_user/whelp/media/
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
